# Generated by Django 4.1.4 on 2022-12-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toperator',
            fields=[
                ('op', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rechargeplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.BigIntegerField()),
                ('description', models.TextField(default='')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recoperator.toperator')),
            ],
        ),
    ]
